FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

ENV CGO_ENABLED=0
ENV GOOS=linux

RUN go build -o api_server ./cmd/ledger-api/main.go

FROM alpine:latest

RUN apk add --no-cache ca-certificates

WORKDIR /app/

COPY --from=builder /app/api_server .

EXPOSE 8080

USER nobody:nobody

CMD /app/api_server
